name: ðŸž Java CI with Gradle [UBUNTU] Selenide Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: 'all_tests'
        type: choice
        options:
          - 'all_tests'
          - 'login'
          - 'LoginWitString'
          - 'LoginWitTable'
          - 'InvalidPassword'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: âœ… âš™ï¸ Install Java version "18"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '18'
      - name: âŽ âŒ›ï¸ Check Java version
        run: java -version
      - name: âŽ âŒ›ï¸ Check JVM version
        run: echo $JAVA_HOME
      - name: âŽ âŒ›ï¸ Check Java Core version
        run: javac -version

      - name: âœ… âš™ï¸ Install Gradle 8.13
        run: |
          wget https://services.gradle.org/distributions/gradle-8.13-bin.zip
          unzip gradle-8.13-bin.zip
          sudo mv gradle-8.13 /opt/gradle
          echo "/opt/gradle/bin" >> $GITHUB_PATH
          gradle --version

      - name: ðŸ—‘ï¸ Remove old Chromedriver
        run: |
          sudo rm -f /usr/local/bin/chromedriver
          sudo rm -rf /usr/bin/chromedriver

      - name: âœ… ðŸš¿ Clean Gradle build
        run: gradle clean
      - name: âœ… ðŸ“‚ List Directories before tests
        if: always()
        run: ls -R
      - name: â–¶ï¸ ðŸž Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" = "all_tests" ]; then
            TAG=""
          elif [ "${{ github.event.inputs.deployment_target }}" = "login" ]; then
            TAG='-Dcucumber.filter.tags=@Login'
          else
            TAG="-Dcucumber.filter.tags=@${{ github.event.inputs.deployment_target }}"
          fi
          echo "Running tests with tag filter: $TAG"
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" gradle clean test "$TAG" > build.log 2>&1 || true

      - name: âœ… ðŸ“‚ List Directories after tests
        if: always()
        run: ls -R
      - name: âœ… ðŸ“¦ Archive [Gradle build log]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-build-log.zip
          path: build.log
      - name: âœ… ðŸ“¦ Archive [Test results]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-results.zip
          path: build/reports/tests/test/*
      - name: âœ… ðŸ“¦ Archive [Test attachments]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-attachments.zip
          path: target/*
      - name: âœ… ðŸ“¦ Archive [Cucumber Report]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report.zip
          path: target/cucumber-reports.html
